- hosts: master
  become: yes
  become_method: sudo
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tags:
  - reset
  - master
  - node
  tasks:
  - name: get all pvcs
    shell: kubectl get --all-namespaces pvc --no-headers -- | awk '{print "--namespace " $1 " pvc/" $2}'
    register: command_results
    when: storage.delete_pvs is defined and storage.delete_pvs
    changed_when: false

  - name: delete all pvcs
    command: kubectl delete {{ item }}
    with_items: "{{command_results.stdout_lines}}"
    when: storage.delete_pvs is defined and storage.delete_pvs

  - name: wait till all pvcs are removed/cleaned
    shell: "kubectl get pvc --no-headers -- || true"
    register: command_result
    until: command_result.stdout == ""
    retries: 10
    delay: 3
    when: storage.delete_pvs is defined and storage.delete_pvs
    changed_when: false

  - name: wait till all pvs are removed/cleaned
    shell: "kubectl get pv --no-headers -- || true"
    register: command_result
    until: command_result.stdout == ""
    retries: 40
    delay: 3
    when: storage.delete_pvs is defined and storage.delete_pvs
    changed_when: false

