---
- include: reset.yml
- include: common.yml
- include: master.yml
- include: node.yml
- include: post_cluster_deploy.yml
- include: helm.yml
- include: rook_clean.yml
- include: rook.yml
- include: sanity.yml
