---
- include: pre_sanity.yml
- include: reset_helm.yml
- include: remove_pvs.yml
- include: reset_nfs.yml
- include: reset_drain.yml
- include: reset.yml
- include: reset-weave.yml
- include: common.yml
- include: master.yml
- include: network.yml
- include: node.yml
- include: post_cluster_deploy.yml
- include: helm.yml
- include: rook_clean.yml
- include: rook.yml
- include: sanity.yml
