---
# - hosts: master
#   become: yes
#   become_method: sudo
#   tags:
#   - k8s_addons
#   tasks:
  - set_fact:
      env_kc: '{{ proxy_env |default({}) | combine ({"KUBECONFIG" :"/etc/kubernetes/admin.conf"}) }}'
    tags:
    - always

  - name: Install k8s_addons_urls (with proxy)
    command: /usr/bin/kubectl apply -f {{ item }}
    with_items: "{{ k8s_addons_urls | default ('') }}"
    environment: '{{env_kc}}'
    when: k8s_addons_urls is defined
    tags:
    - k8s_addons
