---
- name: kubectl aliases to ~/.bash_profile
  lineinfile:
    dest: ~/.bash_profile
    line: "{{ item }}"
    state: present
  when: shell is undefined or shell == 'bash'
  with_items:
  - "alias watch='watch ' "
  - "alias k='kubectl ' "
  - "alias ks='kubectl -n kube-system ' "
  - "alias kg='kubectl get --all-namespaces -o wide '" # --show-labels '"
  - "alias wp='watch kg po '" # -w --show-labels '"
  - "alias wipt='watch -n1 iptables -vnL ' "

- name: Install optional packages like bash-completion
  package: name={{ item }} state={{ package_state | default ('latest') }}
  with_items:
  - bash-completion
  ignore_errors: yes

- name: kubeadm completion preps
  file:
    path: ~/.kube/
    state: directory
    mode: 0755

- name: kubeadm completion shell
  shell: kubeadm completion {{ shell | default ('bash') }} > ~/.kube/kubeadm_completion.bash.inc
  args:
    warn: no

- name: kubeadm completion to ~/.bash_profile
  lineinfile:
    dest: ~/.bash_profile
    line: '[[ -x ${HOME}/.kube/kubeadm_completion.bash.inc ]] && source ${HOME}/.kube/kubeadm_completion.bash.inc'
    state: present
  when: shell is undefined or shell == 'bash'

- name: kubectl completion shell
  shell: kubectl completion {{ shell | default ('bash') }} > ~/.kube/completion.bash.inc
  args:
    warn: no

- name: kubectl completion to ~/.bash_profile
  lineinfile:
    dest: ~/.bash_profile
    line: '[[ -x ${HOME}/.kube/completion.bash.inc ]] && source ${HOME}/.kube/completion.bash.inc'
    state: present
  when: shell is undefined or shell == 'bash'

