---
# TODO automatically detect this with "kubeadm version"
- name: Pull images
  command: /usr/bin/docker pull "{{ item }}:{{ kubernetes_version | default ('latest') }}"
  with_items:
  - "gcr.io/google_containers/kube-proxy-amd64"
  - "gcr.io/google_containers/kube-controller-manager-amd64"
  - "gcr.io/google_containers/kube-apiserver-amd64"
  - "gcr.io/google_containers/kube-scheduler-amd64"
  tags:
  - prepull_images

- name: Generate cluster token
  command: /usr/bin/kubeadm token generate
  register: kubeadm_token_generate
  when: kubeadm_token is not defined

- set_fact: kubeadm_token={{ kubeadm_token_generate.stdout }}
  when: kubeadm_token is not defined

- name: Initialize cluster
  command: /usr/bin/kubeadm init --token {{ kubeadm_token }} --kubernetes-version {{ kubernetes_version | default ('latest') }} --pod-network-cidr={{ pod_network_cidr | default ('10.244.0.0/16') }}

- name: Create cluster network
  command: /usr/bin/kubectl apply -f {{ item }}
  with_items: "{{ kubeadm_network_addons_urls }}"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
    '{{proxy_env.http_proxy}}'
    '{{proxy_env.https_proxy}}'
    '{{proxy_env.no_proxy}}'
    

- name: Wait 1 minute for images pulls and cluster services to start
  pause: minutes=1
