kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-claim
  #annotations: # When not defined, the default storageClass is used (if any defined)
    #volume.beta.kubernetes.io/storage-class: rook-block
    #volume.beta.kubernetes.io/storage-class: thin #vsphere
    #volume.beta.kubernetes.io/storage-class: nfs.k8s
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
